linters:
  enable-all: true
  disable:
    - depguard
    - exportloopref
    - execinquery
    - gomnd
    - funlen
    - containedctx
    - exhaustruct
    - testpackage
    - varnamelen
    - maintidx
    - err113
    - nlreturn
    - wrapcheck
    - tagliatelle
    - paralleltest
    - lll
    - contextcheck
    - gochecknoglobals
    - tagalign
    - nilnil
    - godot
    - godox
    - gci
    - gocognit
    - gocyclo
    - cyclop
    - ireturn
    - gofumpt

linters-settings:
  wsl:
    allow-assign-and-call: false
    strict-append: false
  revive:
    rules:
      - name: blank-imports
        disabled: true
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 9
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 600
  mnd:
    ignored-functions:
      - "context.WithTimeout"
  gocritic:
    disabled-checks:
      - ifElseChain

issues:
  exclude:
    - "if statements should only be cuddled with assignments" # from wsl
    - "if statements should only be cuddled with assignments used in the if statement itself" # from wsl
    - "assignments should only be cuddled with other assignments" # from wsl. false positive case: var a bool\nb := true
    - "declarations should never be cuddled" # from wsl
  exclude-rules:
    - path: _test\.go
      linters:
        - perfsprint
  exclude-dirs:
    - ent
    - apis
