version: "0.2"
ignorePaths:
  - go.sum
  - go.mod
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - apiserver
  - APIURL
  - Balancable
  - bufbuild
  - containedctx
  - contextcheck
  - coreapi
  - coreapiv1
  - cyclop
  - depguard
  - Detailf
  - dupl
  - entgo
  - errorlint
  - execinquery
  - exhaustruct
  - forbidigo
  - funlen
  - gatewayapi
  - gatewayapiv
  - getkin
  - gochecknoglobals
  - gocognit
  - gocritic
  - gocyclo
  - godotenv
  - godox
  - gofumpt
  - gomnd
  - gonanoid
  - googleapis
  - gosec
  - gqlerror
  - gqlgen
  - grpcpkg
  - grpcservers
  - grpcservices
  - ireturn
  - jsonapi
  - jsonfmt
  - jsonschema
  - jwtclaim
  - labstack
  - lingtic
  - lingticio
  - llmg
  - llmgapi
  - Logit
  - Logprob
  - maintidx
  - managementapi
  - managementapiv1
  - mapstructure
  - matoous
  - mitchellh
  - modelv1
  - Nargs
  - nekomeowww
  - nestif
  - Nillable
  - nilnil
  - nlreturn
  - nolint
  - nonamedreturns
  - openai
  - openaiapiv1
  - openapi
  - openapiv2
  - openapiv3
  - paralleltest
  - perfsprint
  - Probs
  - Protobuf
  - protoc_gen_openapiv2
  - protoc-gen-openapiv2
  - protocolbuffers
  - protoiface
  - protovalidate
  - rediskeys
  - Rueidis
  - rueidisstore
  - samber
  - santhosh-tekuri
  - sashabaranov
  - semanticcache
  - serverv1
  - Sortby
  - stretchr
  - stylecheck
  - Supabase
  - tagalign
  - testpackage
  - thumbhash
  - timestamppb
  - Upgrader
  - Upstreamable
  - Upstreams
  - varnamelen
  - vektah
  - wellknowntypes
  - wrapcheck
ignoreWords: []
import:
  - "@cspell/dict-golang"
