version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - apiserver
  - APIURL
  - bufbuild
  - coreapi
  - coreapiv1
  - Detailf
  - entgo
  - gatewayapi
  - gatewayapiv
  - googleapis
  - gqlerror
  - gqlgen
  - grpcpkg
  - grpcservers
  - grpcservices
  - jsonapi
  - jsonfmt
  - jsonschema
  - jwtclaim
  - labstack
  - lingtic
  - lingticio
  - llmg
  - llmgapi
  - managementapi
  - managementapiv1
  - mapstructure
  - mitchellh
  - modelv1
  - Nargs
  - nekomeowww
  - Nillable
  - nolint
  - openai
  - openaiapiv1
  - openapi
  - openapiv2
  - openapiv3
  - Probs
  - Protobuf
  - protocolbuffers
  - protovalidate
  - rediskeys
  - Rueidis
  - rueidisstore
  - samber
  - santhosh-tekuri
  - sashabaranov
  - semanticcache
  - serverv1
  - Sortby
  - Supabase
  - thumbhash
  - timestamppb
  - vektah
  - wellknowntypes
ignoreWords: []
import:
  - "@cspell/dict-golang"
