version: "3.9"

services:
  redis_stack_local:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  # # promtail service that helps services to collect logs
  # # you can uncomment the following lines if you want to enable promtail
  # promtail:
  #   image: grafana/promtail:2.8.2
  #   restart: unless-stopped
  #   volumes:
  #     - ./production/promtail:/etc/promtail # you may edit the ./production/promtail/config.yaml file to suit your needs
  #     - logs/node-api-server:/var/log/services/node-api-server:ro
  #   command: >
  #     -config.file=/etc/promtail/config.yaml

  #   # uncomment the following lines if you want to view the web ui of promtail
  #   # ports:
  #   #   - 9080:9080
  #   # uncomment the following lines if you want to use your own loki service
  #   # networks:
  #   #   - <loki_network> # replace <loki_network> with your own loki network name
#
# uncomment the following lines if you want to use your own loki service
# that live in another docker-compose.yml file
# networks:
#   <loki_network>: # replace <loki_network> with your own loki network name
#     external: true
